version: 2
jobs:
  build:
    working_directory: ~/mpesa_api
    docker:
      - image: circleci/python:3.6.1
        environment:
          DB_USER: circleci
          DB_NAME: circle_test
          DB_PASSWORD: "root"
          DB_HOST: 127.0.0.1
          DB_PORT: 5432
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: "root"
      - image: brandembassy/rabbitmq:latest

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install codecov


      # run tests!
      - run:
          name: run app tests
          command: |
            . venv/bin/activate
            python manage.py check --settings=config.settings.ci
            python manage.py migrate --settings=config.settings.ci
            coverage xml
            coverage run manage.py test mpesa_api.core.tests --settings=config.settings.ci
      - run:
          name: upload codecov report
          command: bash <(curl -s https://codecov.io/bash) -t 65a50f05-6f90-4a02-8a44-f9e0cfd76a58